version: 2

before:
  hooks:
    - go mod tidy

builds:
  - id: cpuset
    main: ./cmd/cpuset
    binary: cpuset
    flags:
      - -trimpath
    ldflags:
      - -s -w
    env:
      - CGO_ENABLED=0
    goos:
      - linux
    goarch:
      - amd64
      - arm
      - arm64
    goarm:
      - 7
    mod_timestamp: "{{ .CommitTimestamp }}"

archives:
  - formats:
      - binary
    name_template: >-
      {{- .Binary }}-
      {{- title .Os }}-
      {{- if eq .Arch "amd64" }}x86_64
      {{- else if eq .Arch "arm64" }}aarch64
      {{- else }}{{ .Arch }}{{ end }}
      {{- if .Arm }}v{{ .Arm }}{{ end -}}

changelog:
  disable: true

checksum:
  disable: true
