name: Lint, test and release

on: push

env:
  DEVBOX_USE_VERSION: '0.13.7'

jobs:
  lint-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install devbox
        uses: jetify-com/devbox-install-action@v0.11.0
      - name: Run the lint script
        run: devbox run lint
      - name: Run the test script
        run: devbox run test

  release:
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/tags/')
    needs: lint-test
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
      - name: Install devbox
        uses: jetify-com/devbox-install-action@v0.11.0
      - name: Run the release script
        run: devbox run release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
